# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-04 10:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='clientRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_requested', models.DateTimeField(auto_now_add=True)),
                ('date_processed', models.DateTimeField(null=True)),
                ('status', models.CharField(choices=[('0', 'Очаква обработка'), ('1', 'В печат'), ('2', 'Очаква куриер'), ('3', 'Изпратена'), ('4', 'Очаква потвърждение от офис')], default='0', max_length=150)),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='clientUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_address', models.CharField(default='', max_length=500)),
                ('contact', models.CharField(default='', max_length=500)),
                ('role', models.CharField(default='user', max_length=30)),
                ('avatar', models.ImageField(upload_to='avatar/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerProjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('price_per_item', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('legal_name', models.CharField(max_length=500)),
                ('legal_address', models.CharField(max_length=700)),
                ('legal_EIK', models.CharField(max_length=50)),
                ('projects_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_projects', to='system.CustomerProjects')),
            ],
        ),
        migrations.CreateModel(
            name='ItemType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_items', to='system.Customers')),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_project_items', to='system.CustomerProjects')),
            ],
        ),
        migrations.CreateModel(
            name='requestElement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('item_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_item', to='system.ItemType')),
                ('request_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_element', to='system.clientRequest')),
            ],
        ),
    ]
